name: lal-development-py27
channels:
  - conda-forge
dependencies:
  - autoconf
  - automake = 1.15
  - bc
  - cfitsio
  - clang_osx-64
  - doxygen
  - fftw
  - freezegun
  - gsl
  - h5py
  - hdf5
  - healpy
  - ldas-tools-framecpp
  - libframe
  - ligo-segments
  - lscsoft-glue
  - make
  - metaio
  - mock
  - numpy
  - pkg-config
  - pytest
  - python = 2.7
  - scipy
  - six
  - swig >= 3.0.10
  - texlive-core
  - zlib
